# Generated by Django 4.2 on 2023-04-27 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doc_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(auto_created=True)),
                ('name', models.CharField(max_length=100)),
                ('filepath', models.CharField(max_length=300)),
            ],
        ),
    ]
