# Generated by Django 4.2 on 2023-04-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='doc_manage',
            new_name='Docmanage',
        ),
    ]
