# Generated by Django 4.2 on 2023-04-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manage', '0002_rename_doc_manage_docmanage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docmanage',
            name='filepath',
        ),
        migrations.RemoveField(
            model_name='docmanage',
            name='index',
        ),
        migrations.CreateModel(
            name='DocAttached',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attached', models.FileField(upload_to='uploads/file/%Y/%m/%d/')),
                ('doc_mng', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_manage.docmanage')),
            ],
        ),
    ]
