# Generated by Django 4.2 on 2023-04-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manage', '0003_remove_docmanage_filepath_remove_docmanage_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docattached',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
