# Generated by Django 4.2 on 2023-05-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manage', '0004_docattached_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='docmanage',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=1),
            preserve_default=False,
        ),
    ]
